name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create local.properties
      run: |
        echo "etherscan.testnet.api.key=${{ secrets.ETHERSCAN_TESTNET_API_KEY }}" >> local.properties
        echo "etherscan.mainnet.api.key=${{ secrets.ETHERSCAN_MAINNET_API_KEY }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleProductionMainnetRelease assembleProductionMainnetDebug

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-productionMainnet-release
        path: composeApp/build/outputs/apk/productionMainnet/release/*.apk

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-productionMainnet-debug
        path: composeApp/build/outputs/apk/productionMainnet/debug/*.apk
